name: Trigger Claude Enhancement
on:
  issues:
    types: [opened, edited]

jobs:
  trigger-claude:
    if: contains(join(github.event.issue.labels.*.name, ','), 'needs-ai')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Trigger Claude GitHub App
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const issueTitle = context.payload.issue.title;
            const issueBody = context.payload.issue.body;
            const labels = context.payload.issue.labels.map(label => label.name);

            // Determine content type
            let contentType = 'content';
            let template = 'template';

            if (issueTitle.includes('[TASK]') || labels.includes('task')) {
              contentType = 'task';
              template = 'templates/task-template.md';
            } else if (issueTitle.includes('[PROJECT]') || labels.includes('project')) {
              contentType = 'project';
              template = 'templates/project-template.md';
            } else if (issueTitle.includes('[NOTE]') || labels.includes('note')) {
              contentType = 'note';
              template = 'templates/note-template.md';
            } else if (issueTitle.includes('[GOAL]') || labels.includes('goal')) {
              contentType = 'goal';
              template = 'templates/goal-template.md';
            }

            const commentBody = '@claude Please enhance this ' + contentType + ' and CREATE A PULL REQUEST with the enhanced file.\n\n' +
              '**SPECIFIC INSTRUCTIONS:**\n' +
              '1. Read the template from: ' + template + '\n' +
              '2. Enhance the ' + contentType + ' content using the template structure\n' +
              '3. CREATE A NEW FILE in the content/' + contentType + 's/ directory\n' +
              '4. Use filename convention: ' + (contentType === 'task' || contentType === 'note' ? 'YYYY-MM-DD-title.md' : 'title.md') + '\n' +
              '5. OPEN A PULL REQUEST with the new file\n' +
              '6. Close this issue when done\n\n' +
              '**IMPORTANT:** Do not just respond with text - actually create the file and PR!\n\n' +
              '**Content Type:** ' + contentType.toUpperCase() + '\n' +
              '**Template:** ' + template + '\n' +
              '**Target Directory:** content/' + contentType + 's/\n\n' +
              'Please CREATE the enhanced file and OPEN A PULL REQUEST now!';

            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });