name: Claude Code Content Enhancement
on:
  issues:
    types: [opened, edited]

jobs:
  enhance-content:
    if: contains(join(github.event.issue.labels.*.name, ','), 'needs-ai')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            You are a life management assistant that helps organize and enhance content for a GitHub-based life management system.

            **Issue Information:**
            - Title: "${{ github.event.issue.title }}"
            - Body: "${{ github.event.issue.body }}"
            - Labels: "${{ join(github.event.issue.labels.*.name, ', ') }}"
            - Issue Number: #${{ github.event.issue.number }}

            **Your Tasks:**
            1. **Analyze the content type** from the title prefix ([TASK], [PROJECT], [NOTE], [GOAL]) or labels
            2. **Read the appropriate template** from the templates/ directory
            3. **Enhance and structure the content** by:
               - Improving clarity and grammar
               - Adding missing details that would be helpful
               - Organizing information logically
               - Suggesting relevant tags and categories
               - Adding cross-references to related content if applicable
            4. **Create or update the appropriate file** in the content/ directory structure:
               - content/tasks/ for tasks
               - content/projects/ for projects
               - content/notes/ for notes
               - content/goals/ for goals
            5. **Use consistent naming**: Use kebab-case filenames with dates when relevant
            6. **Create a pull request** with the enhanced content
            7. **Close the original issue** with a comment explaining what was created

            **Content Enhancement Guidelines:**
            - For TASKS: Focus on actionability, priority, dependencies, and clear completion criteria
            - For PROJECTS: Emphasize goals, milestones, resources, and success metrics
            - For NOTES: Improve organization, add relevant headers, and suggest follow-up actions
            - For GOALS: Add SMART criteria, break down into actionable steps, and define success metrics

            **File Naming Convention:**
            - Tasks: `YYYY-MM-DD-task-title.md`
            - Projects: `project-name.md`
            - Notes: `YYYY-MM-DD-note-title.md`
            - Goals: `goal-title.md`

            Please proceed to enhance and organize this content!

          claude_args: |
            --max-turns 10
            --allowedTools "Read,Write,Edit,Glob,Grep,Bash(git *:*),MultiEdit"